FOLDER_NAME = "costmap_v4"
model_path = f"model/{FOLDER_NAME}"
# model_path = f"model/costmap_v2"
gifs_path = f"results/{FOLDER_NAME}/gifs"
trajectory_path = f"results/{FOLDER_NAME}/trajectory"
length_path = f"results/{FOLDER_NAME}/length"
INPUT_DIM = 8  # 7
EMBEDDING_DIM = 128
K_SIZE = 20  # the number of neighbors
USE_GPU = True  # do you want to use GPUS?
NUM_GPU = 1  # the number of GPUs
NUM_META_AGENT = 8  # the number of processes
NUM_TEST = 200
NUM_RUN = 1  # 1
SAVE_GIFS = True  # do you want to save GIFs
SAVE_TRAJECTORY = True  # do you want to save per-step metrics
SAVE_LENGTH = True  # do you want to save per-episode metrics
